//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPCReportingTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPCReportingTool.Resources.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        internal static string ApplyChangesBtn {
            get {
                return ResourceManager.GetString("ApplyChangesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date should be later than the start date.
        /// </summary>
        internal static string DateErrorEnd {
            get {
                return ResourceManager.GetString("DateErrorEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date should be earlier than the end date.
        /// </summary>
        internal static string DateErrorStart {
            get {
                return ResourceManager.GetString("DateErrorStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Qty.
        /// </summary>
        internal static string DBBatchQtyReportView {
            get {
                return ResourceManager.GetString("DBBatchQtyReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string DBCommentDefectView {
            get {
                return ResourceManager.GetString("DBCommentDefectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Code.
        /// </summary>
        internal static string DBDefectCodeDefectView {
            get {
                return ResourceManager.GetString("DBDefectCodeDefectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string DBEndDateReportView {
            get {
                return ResourceManager.GetString("DBEndDateReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Type.
        /// </summary>
        internal static string DBErrorDefectView {
            get {
                return ResourceManager.GetString("DBErrorDefectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ErrorType (ENG)].
        /// </summary>
        internal static string DBErrorFieldDefectsView {
            get {
                return ResourceManager.GetString("DBErrorFieldDefectsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Type.
        /// </summary>
        internal static string DBInspectionTypeReportView {
            get {
                return ResourceManager.GetString("DBInspectionTypeReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector ID.
        /// </summary>
        internal static string DBInspectorIDReportView {
            get {
                return ResourceManager.GetString("DBInspectorIDReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector Name.
        /// </summary>
        internal static string DBInspectorNameReportView {
            get {
                return ResourceManager.GetString("DBInspectorNameReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [InspectionType (ENG)].
        /// </summary>
        internal static string DBInspFieldDefectsView {
            get {
                return ResourceManager.GetString("DBInspFieldDefectsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name_ENG.
        /// </summary>
        internal static string DBNameColumn {
            get {
                return ResourceManager.GetString("DBNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Order.
        /// </summary>
        internal static string DBProdOrderReportView {
            get {
                return ResourceManager.GetString("DBProdOrderReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string DBProductReportView {
            get {
                return ResourceManager.GetString("DBProductReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Checked.
        /// </summary>
        internal static string DBQtyCheckedReportView {
            get {
                return ResourceManager.GetString("DBQtyCheckedReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Defective.
        /// </summary>
        internal static string DBQtyDefectiveReportView {
            get {
                return ResourceManager.GetString("DBQtyDefectiveReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string DBReferenceDefectView {
            get {
                return ResourceManager.GetString("DBReferenceDefectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report ID.
        /// </summary>
        internal static string DBReportIDReportView {
            get {
                return ResourceManager.GetString("DBReportIDReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string DBStartDateReportView {
            get {
                return ResourceManager.GetString("DBStartDateReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Step.
        /// </summary>
        internal static string DBStepDefectView {
            get {
                return ResourceManager.GetString("DBStepDefectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ManufacturingStep (ENG)].
        /// </summary>
        internal static string DBStepFieldDefectsView {
            get {
                return ResourceManager.GetString("DBStepFieldDefectsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defect(s) registered.
        /// </summary>
        internal static string DefectCountLbl {
            get {
                return ResourceManager.GetString("DefectCountLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string DefectViewerCol1 {
            get {
                return ResourceManager.GetString("DefectViewerCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Step.
        /// </summary>
        internal static string DefectViewerCol2 {
            get {
                return ResourceManager.GetString("DefectViewerCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Type.
        /// </summary>
        internal static string DefectViewerCol3 {
            get {
                return ResourceManager.GetString("DefectViewerCol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Code.
        /// </summary>
        internal static string DefectViewerCol4 {
            get {
                return ResourceManager.GetString("DefectViewerCol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string DefectViewerCol5 {
            get {
                return ResourceManager.GetString("DefectViewerCol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string DefectViewerCol6 {
            get {
                return ResourceManager.GetString("DefectViewerCol6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report will be deleted from the database and it will not be possible to undo this action..
        /// </summary>
        internal static string DeleteReportConf {
            get {
                return ResourceManager.GetString("DeleteReportConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during report deletion.
        /// </summary>
        internal static string DeleteReportErr {
            get {
                return ResourceManager.GetString("DeleteReportErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDateFilter {
            get {
                return ResourceManager.GetString("EndDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Edit Mode.
        /// </summary>
        internal static string EnterEditModeBtn {
            get {
                return ResourceManager.GetString("EnterEditModeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Edit Mode.
        /// </summary>
        internal static string ExitEditModeBtn {
            get {
                return ResourceManager.GetString("ExitEditModeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Header - Report.
        /// </summary>
        internal static string HeaderEditTitle {
            get {
                return ResourceManager.GetString("HeaderEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Date Filter.
        /// </summary>
        internal static string NoDateFilter {
            get {
                return ResourceManager.GetString("NoDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 defect(s) registered.
        /// </summary>
        internal static string NoDefectLbl {
            get {
                return ResourceManager.GetString("NoDefectLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No defect selected.
        /// </summary>
        internal static string NoDefectSelectedErr {
            get {
                return ResourceManager.GetString("NoDefectSelectedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders found for the product.
        /// </summary>
        internal static string NoOrderErr {
            get {
                return ResourceManager.GetString("NoOrderErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the product code before looking for orders.
        /// </summary>
        internal static string NoProductSelectedErr {
            get {
                return ResourceManager.GetString("NoProductSelectedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No row selected. Please select an row.
        /// </summary>
        internal static string NoRowSelectedErr {
            get {
                return ResourceManager.GetString("NoRowSelectedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will remove all the defects that you have registered and it cannot be undone..
        /// </summary>
        internal static string RemoveAllDefectConf {
            get {
                return ResourceManager.GetString("RemoveAllDefectConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data will be send to the Database. Please validate the data and press &quot;Confirm&quot; if everything is OK..
        /// </summary>
        internal static string SendDataConf {
            get {
                return ResourceManager.GetString("SendDataConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during report insertion.
        /// </summary>
        internal static string SendDataErr {
            get {
                return ResourceManager.GetString("SendDataErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDateFilter {
            get {
                return ResourceManager.GetString("StartDateFilter", resourceCulture);
            }
        }
    }
}
